### ISSUE TITLE
False positive in d10/ex05

### ISSUE THREAD

**Issue by amalliar** [mirror12k/42us-stupidity#17]
"Create a function ft_is_sort which returns 1 if the array is sorted and 0 if it isn’t." - the task does not say it has to be sorted in ascending order, yet the test expects descending arrays to be counted as "not sorted".

**Comment by mirror12k** [comment]
all of the ft functions are based on the std-lib functions, and standard definition of sorted is in ascending order (https://en.cppreference.com/w/cpp/algorithm/is_sorted). that said, i can't possibly solve this issue as I'm not maintaining this project, nor am I at 42 to check anything. sorry : (
