### ISSUE TITLE
d11 ex05

### ISSUE THREAD

**Issue by bsemexan** [mirror12k/42us-stupidity#2]
the command line arguments are suppose to include the ./ argument so, argv[0] should be included

**Comment by mirror12k** [comment]
i believe i fixed this issue in question for ex05, but it's hard to tell as i don't have the materials on hand. thanks!

**Comment by bsemexan** [comment]
which material would you need?

**Comment by mirror12k** [comment]
just the exercise to test this. it would be helpful if you could test it out and verify if it works.
